services:
  - type: web
    name: cinegenie
    env: python
    pythonVersion: 3.9.18
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: TMDB_API_KEY
        sync: false 